// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3ojUZzlT3bR1ljbCJJwnclRvIfmP76tw',
    appId: '1:981258504919:web:1bea4c36f91b8847383e92',
    messagingSenderId: '981258504919',
    projectId: 'flutter-push-notificatio-c0c45',
    authDomain: 'flutter-push-notificatio-c0c45.firebaseapp.com',
    storageBucket: 'flutter-push-notificatio-c0c45.firebasestorage.app',
    measurementId: 'G-54NSLPC15J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDma7eKK-cw3NKXsArNPRGL2yTlhqqXMMg',
    appId: '1:981258504919:android:75e074453f5259ed383e92',
    messagingSenderId: '981258504919',
    projectId: 'flutter-push-notificatio-c0c45',
    storageBucket: 'flutter-push-notificatio-c0c45.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQBmovVKfP13kS6W_1RH-EBp0YV7wSK9o',
    appId: '1:981258504919:ios:d2520fb0b1511d64383e92',
    messagingSenderId: '981258504919',
    projectId: 'flutter-push-notificatio-c0c45',
    storageBucket: 'flutter-push-notificatio-c0c45.firebasestorage.app',
    iosBundleId: 'com.example.multiVendorECommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQBmovVKfP13kS6W_1RH-EBp0YV7wSK9o',
    appId: '1:981258504919:ios:d2520fb0b1511d64383e92',
    messagingSenderId: '981258504919',
    projectId: 'flutter-push-notificatio-c0c45',
    storageBucket: 'flutter-push-notificatio-c0c45.firebasestorage.app',
    iosBundleId: 'com.example.multiVendorECommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3ojUZzlT3bR1ljbCJJwnclRvIfmP76tw',
    appId: '1:981258504919:web:ca13bfd2667754b9383e92',
    messagingSenderId: '981258504919',
    projectId: 'flutter-push-notificatio-c0c45',
    authDomain: 'flutter-push-notificatio-c0c45.firebaseapp.com',
    storageBucket: 'flutter-push-notificatio-c0c45.firebasestorage.app',
    measurementId: 'G-XZ35X8TV1K',
  );

}